package de.adesso.objectfieldcoverage.core.finder.lombok;


import de.adesso.objectfieldcoverage.api.AccessibilityAwareFieldFinder;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import spoon.reflect.declaration.CtField;
import spoon.reflect.declaration.CtType;
import spoon.reflect.declaration.CtTypedElement;

import java.util.Collection;
import java.util.Objects;
import java.util.Set;

/**
 * {@link AccessibilityAwareFieldFinder} finding fields which are either directly annotated with Lombok's
 * {@link Getter} annotation or their declaring type is annotated with {@link Getter} or {@link Data}.
 *
 * @see LombokGetterMethodGenerator
 */
public class LombokAccessibilityAwareFieldFinder extends AccessibilityAwareFieldFinder {

    /**
     * The getter method generator which is used to generate lombok getter methods.
     */
    private final LombokGetterMethodGenerator lombokGetterMethodGenerator;

    /**
     * Default no-arg constructor initializing the internal {@link LombokGetterMethodGenerator}
     * with a {@link LombokGetterMethodGeneratorImpl}.
     */
    public LombokAccessibilityAwareFieldFinder() {
        this.lombokGetterMethodGenerator = new LombokGetterMethodGeneratorImpl();
    }

    /**
     *
     * @param lombokGetterMethodGenerator The {@link LombokGetterMethodGenerator} which should be used
     *                                    internally, not {@code null}.
     */
    public LombokAccessibilityAwareFieldFinder(LombokGetterMethodGenerator lombokGetterMethodGenerator) {
        this.lombokGetterMethodGenerator = Objects.requireNonNull(lombokGetterMethodGenerator,
                "lombokGetterMethodGenerator cannot be null");
    }

    /**
     *
     * @param accessingType
     *          The class whose methods could potentially access the given {@code type}'s
     *          fields, not {@code null}.
     *
     * @param field
     *          The field to check, not {@code null}.
     *
     * @return
     *          {@code true}, if the given field has a generated getter which is accessible
     *          by the given {@code accessingType}. {@code false} is returned otherwise.
     */
    @Override
    public boolean isFieldAccessible(CtType<?> accessingType, CtField<?> field) {
        return this.hasAccessibleGeneratedGetter(accessingType, field);
    }

    /**
     *
     * @param accessingType
     *          The type whose methods can access the given {@code field},
     *          not {@code null}.
     *
     * @param field
     *          The field which can be accessed by inside the given {@code accessingType},
     *          not {@code null}.
     *
     * @param <T>
     *          The type of the field.
     *
     * @return
     *          A set containing the getter method generated by lombok as its only
     *          element.
     *
     * @see LombokGetterMethodGenerator#generateGetterMethod(CtField, AccessLevel)
     */
    @Override
    public <T> Collection<CtTypedElement<T>> findAccessGrantingElements(CtType<?> accessingType, CtField<T> field) {
        var getterAccessLevel = getAccessLevelOfGeneratedGetter(field);
        return Set.of(lombokGetterMethodGenerator.generateGetterMethod(field, getterAccessLevel));
    }

    /**
     * Returns {@code true} if one of the following conditions is fulfilled for the generated getter:
     * <ul>
     *     <li>the getter is declared <i>public</i></li>
     *     <li>the getter is declared <i>protected</i> and the {@code accessingType} is in the same
     *     package as or a sub-class of the {@code field}'s declaring type</li>
     *     <li>the getter is declared <i>package private</i> and the {@code accessingType} is in the same
     *     package as or an inner class of the {@code field}'s declaring type</li>
     *     <li>the getter is declared <i>private</i> and the {@code accessingType} is an inner class
     *     of the {@code field}'s declaring type</li>
     * </ul>
     *
     * See §6.6.1 of the Java Language Specification for more details on why this is implemented
     * this way.
     *
     * <b>Note:</b> {@link AccessLevel#MODULE} and {@link AccessLevel#PACKAGE} are regarded as
     * equal.
     *
     * @param accessingType
     *          The type whose methods could potentially access the given {@code field},
     *          not {@code null}.
     *
     * @param field
     *          The field to check, not {@code null}.
     *
     * @return
     *          {@code true}, if lombok generates a getter which is accessible from the given
     *          {@code accessingType}' methods. {@code false} is returned otherwise.
     *
     * @see LombokGetterMethodGenerator#isGetterMethodWithDifferentAccessModifierPresent(CtField, AccessLevel)
     */
    private boolean hasAccessibleGeneratedGetter(CtType<?> accessingType, CtField<?> field) {
        if(!isFieldOrDeclaringClassAnnotatedWithGetter(field)) {
            return false;
        }

        var accessLevel = this.getAccessLevelOfGeneratedGetter(field);

        if(lombokGetterMethodGenerator.isGetterMethodWithDifferentAccessModifierPresent(field, accessLevel)) {
            return false;
        }

        switch (accessLevel) {
            case PUBLIC:
                return true;
            case PROTECTED:
                return isInSamePackageAsDeclaringType(field, accessingType) || isRealSubClassOfDeclaringClass(field, accessingType);
            case PACKAGE: case MODULE:
                return isInSamePackageAsDeclaringType(field, accessingType) || isInnerClassOfDeclaringType(field, accessingType);
            case PRIVATE:
                return isInnerClassOfDeclaringType(field, accessingType);
            default:
                return false;
        }
    }

    /**
     *
     * @param field
     *          The field to check, not {@code null}.
     *
     * @return
     *          {@code true}, if the given {@code field} is annotated with {@link Getter}
     *          or the fields declaring type is annotated with {@link Getter} or {@link Data}. {@code false}
     *          is returned otherwise.
     */
    private boolean isFieldOrDeclaringClassAnnotatedWithGetter(CtField<?> field) {
        if(field.getAnnotation(Getter.class) != null) {
            return true;
        }

        var declaringType = field.getDeclaringType();
        return declaringType.getAnnotation(Getter.class) != null ||
                declaringType.getAnnotation(Data.class) != null;
    }

    /**
     * See Lombok's <a href="https://projectlombok.org/features/GetterSetter">Getter</a> and
     * <a href="https://projectlombok.org/features/Data">Data</a> documentation for more details.
     *
     * @param field
     *          The field to get the access level of the generated getter for, not
     *          {@code null}.
     *
     * @return
     *          The access level specified in the Getter annotation of the field (if present),
     *          the access level specified in the Getter annotation of the declaring type (if present)
     *          or {@link AccessLevel#PUBLIC} otherwise, since the declaring type must be annotated
     *          with {@link Data} then and the access level can't be specified. Exactly in that order.
     */
    private AccessLevel getAccessLevelOfGeneratedGetter(CtField<?> field) {
        var fieldGetterAnnotation = field.getAnnotation(Getter.class);

        if(Objects.nonNull(fieldGetterAnnotation)) {
            return fieldGetterAnnotation.value();
        }

        var declaringTypeGetterAnnotation = field.getDeclaringType()
                .getAnnotation(Getter.class);
        if(Objects.nonNull(declaringTypeGetterAnnotation)) {
            return declaringTypeGetterAnnotation.value();
        }

        return AccessLevel.PUBLIC;
    }

}
