name: Java CI

on: [push]

env:
  SPOON_ARTIFACT_NAME: spoon-core-8.1.1-SNAPSHOT

jobs:
  build-spoon-artifact:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
        with:
          repository: 'https://github.com/dnl50/spoon.git'
          ref: 'spoon-core-8.1.0-equals-fix'
          path: 'spoon-core'
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      
      - name: Cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      
      - name: Build spoon artifact without running tests
        run: mvn -f spoon-core/pom.xml clean package -Djar.finalName=$SPOON_ARTIFACT_NAME -DskipTests -P release
      
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: spoon-core
          path: spoon-core/target/${{env.SPOON_ARTIFACT_NAME}}.jar

  build:
    runs-on: ubuntu-latest
    needs: build-spoon-artifact
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Download spoon artifact
        uses: actions/download-artifact@v1
        with:
          name: spoon-core
          
      - name: Copy artifact to local maven repository
        run: |
          mkdir -p lib
          mv spoon-core/${{env.SPOON_ARTIFACT_NAME}}.jar lib/
      
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Build with Gradle
        run: ./gradlew build
